[package]
name = "rust-calculator"
version = "0.1.0"
atuhors = ["Alexandre"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.5"
rand = "0.8"

[build-dependencies]
slint-build = "1.5"
